const courses_names = [
    "CEC510 - Term Project",
"CSO507 - Deep Learning",
"CSD516 - Optimization Techniques",
"CEC509 - Advanced Testing Laboratory",
"CED528 - Structural Dynamics",
"CSO501 - Principles of Artificial Intelligence",
"CSD515 - Multimedia Systems and Security",
"CED530 - Hydrogeology and Well Hydraulics",
"CED529 - Advanced Foundation Engineering",
"CED532 - Slope and Retaining Structure",
"CED533 - Hydroclimatology",
"CED534 - Theory of Elastic Stability",
"CED535 - Soil Dynamics",
"CED542 - Prestressed Concrete Structures",
"ECC507 - Electronics Engineering - I Lab",
"CEO531 - Railway Geotechnics",
"ECC508 - Electronics Engineering - II Lab",
"CEO524 - Finite Element Method",
"ECD503 - Wireless Communication Systems",
"ECD500 - Advanced Signal Processing",
"ECD541 - Microwave Measurements",
"ECD504 - Computer Communication Networks",
"ECD520 - Optoelectronic and Photonics Devices",
"ECD514 - Photonic Sensors",
"ECD505 - CAD for VLSI",
"ECD560 - Analog IC Design",
"ECD531 - Photonic Integrated Circuits",
"ECD569 - MOS Device Physics and Modelling",
"ECD564 - On-Chip Interconnects",
"ECO560 - Test and Verification of VLSI Circuits",
"ECO520 - Optical Networks",
"EEO501 - Smart Grid Technology",
"EEC514 - Advanced Power System Protection Lab",
"EEC513 - Advanced power System Simulation Lab",
"EEC508 - Power Electronic Converters",
"EEC501 - Power System Analysis",
"EED504 - Wireless Power Transfer",
"EEO503 - Electric & Hybrid Electric Vehicles",
"ESC506 - Environmental Laws and Impact Assessment",
"ESC507 - Municipal Solid Waste Management",
"ESC523 - Water and Wastewater Engineering Practical",
"ESD503 - Environmental Modelling",
"ESC524 - Soil and Microbiology Practical",
"ESO501 - Environmental Management System and Auditing",
"FMD525 - Iron and Steel Making",
"FMC556 - Materials Characterization Laboratory",
"FMC553 - Fuel Technology Laboratory",
"ESO502 - Environmental Aspects of Industries",
"FMO550 - Microwave Processing of Minerals and Fuels",
"FMD533 - Energy Conservation Processes",
"HSC512 - Quantitative Techniques for Social Sciences",
"HSO501 - Cognitive Psychology",
"FMD531 - Alternate Energy Systems",
"HSD539 - Introduction to Cognitive Linguistics",
"FMD540 - Size Enlargement Processes",
"HSO513 - Environment, Development and Politics",
"MCC540 - Neural Networks and Deep Learning",
"MCC541 - Advanced DBMS Practical",
"MCC542 - Neural Networks and Deep Learning Practical",
"MCC539 - Advanced DBMS",
"MCO531 - Stochastic Processes",
"MCD533 - Numerical Optimization",
"HSO506 - Indian Society and Culture",
"HSD555 - Gender in Organization",
"MNC508 - Geostatistics and Mine Valuation",
"HSO508 - Digital Society",
"MND500 - Managerial Decision Making",
"MNC503 - Mine Planning and Design",
"MNC506 - Computer Aided Mine Planning and Design Practical",
"HSD512 - Gender Studies",
"HSD507 - Introduction to Drama, Theatre and Performance Studies",
"MND501 - Mine Simulation and Data Analytics",
"MNC509 - Mine Simulation and Data analytics Practical",
"MED509 - Advanced Thermodynamics",
"MNO501 - Mining, Energy and Climate Change",
"FMD541 - Processing Equipment Selection",
"MNO510 - Rock Excavation Technology",
"MEC510 - Mechanical Engineering Lab - II",
"MEC509 - Mechanical Engineering Lab - I",
"MED542 - Finite Element Method in Thermal Engineering",
"MEO579 - Computational Fluid Dynamics",
"MED538 - Gas Dynamics",
"MSC515 - Software Lab",
"MEO586 - Additive Manufacturing",
"MED503 - Finite Element Method",
"MSC517 - Simulation Modelling & Analysis Lab",
"MED519 - Engineering Tribology",
"MSC520 - Quality Management",
"MSC519 - Project Management",
"MMC510 - Earth Moving Equipment Lab",
"MSC527 - Machine Learning",
"MMC511 - Numerical Simulation Lab",
"MMC509 - Maintenance Engineering",
"MMC508 - Mining Machinery Design",
"CHD503 - Catalysts & Materials Characterization Techniques",
"CHD501 - Membrane Technology",
"CHD507 - Modelling & Simulation",
"CHD505 - Interfacial and Colloidal Phenomena",
"PEC510 - Petroleum Instrumentation and Measurements Practical",
"PEC511 - Development of Working Models Practical",
"PEO501 - Fluid Flow through Porous Media",
"PED501 - Reservoir Simulation",
"PEC509 - Advanced Drilling Technology",
"GPD521 - Time Series Analysis in Geosciences",
"GLD551 - Elements of Rock Engineering",
"GLD540 - Geomorphology",
"MSD528 - Advanced Decision Modelling",
"PEC508 - Petroleum Geomechanics and Hydraulic Fracturing",
"MSD526 - Supply Chain Management",
"CEO530 - Sustainable Engineering",
"CYD507 - Bio-inorganic Chemistry",
"CEO529 - Blast Protection of Structures",
"ECD510 - Quantum Computation",
"PEO503 - Unconventional Hydrocarbon Resources",
"ECO501 - Internet of Things",
"CSO502 - Data Analytics",
"CSD503 - Computational Number Theory",
"CSD519 - Software Testing",
"MCO533 - Numerical Linear Algebra",
"EED502 - Advanced Machine Drives",
"ESD506 - Biomedical and Hazardous Waste Management",
"CHC210 - Heat Transfer Lab",
"EED501 - Design of Power Converters",
"MND505 - Geospatial Technologies for Natural Resources",
"ESO505 - Climate Change and Modelling",
"MND504 - Modelling and Analysis of Geospatial data",
"MND511 - Modern Blasting Technology in Mining",
"CHC209 - Process Dynamics and Control",
"HSO510 - Judgement and Decision Making",
"MMC211 - Manufacturing Technology and Soft Computing Lab",
"CHC207 - Principles of Mass Transfer",
"PHD503 - High Energy Physics",
"GLC514 - Igneous and Metamorphic Petrology Practical",
"FMO546 - Mechanochemistry in Nanoscience and Materials Engineering",
"PHD506 - Characterization Techniques",
"MED546 - Conduction and Radiation",
"MED515 - Theory of Metal Forming",
"CSC209 - Operating Systems",
"MND547 - Mine Automation",
"HSO503 - Technology, Culture and Society",
"CHC206 - Chemical Engineering Thermodynamics",
"ESC254 - Soil  and Environmental Microbiology Practical",
"FMO541 - Characterization of Materials",
"MEO581 - Fundamentals of Combustion",
"MSD505 - Materials Management",
"HSD525 - Advance Course in Applied Ethics",
"PED504 - Profile Modification & Water Shutoff",
"MEO534 - Automation and Control",
"GLC513 - Coal Geology",
"GLC509 - Igneous Petrology",
"GLC511 - Applied Sedimentology",
"HSI500 - Research and Technical Communication",
"HSI500 - Research and Technical Communication",
"CHC211 - Process Control Lab",
"CSC210 - Algorithm Design & Analysis Lab",
"CSC206 - Algorithm Design & Analysis",
"CSC211 - Operating Systems Lab",
"GPC513 - Geoelectrical Methods Practical",
"CHC208 - Chemical Process Technology",
"GLC514 - Igneous and Metamorphic Petrology Practical",
"EEC273 - Control and Measurement lab",
"CSC208 - Theory of Computation",
"CHE202 - Transport Phenomena",
"CSC207 - Computer Architecture",
"GLC515 - Sedimentology and Petroleum Geology Practical",
"GPE201 - Earth and Planetary System",
"GLC512 - Petroleum Geology",
"PHD400 - Photonics & Optoelectronics",
"MNC504 - Risk and Workplace Safety Management",
"EEC274 - Electrical Machines and Power lab",
"MEC507 - Incompressible and Compressible Flow",
"CSE202 - Object Oriented Programming",
"HSO301 - Ethical Issues in Sceince",
"ESC206 - Environmental Policy and Legislation",
"PHO502 - Nonlinear Optics",
"PHO503 - Physics of Nanomaterials",
"HSC503 - Seminar",
"GPC522 - Magnetic Method Practical",
"GPC208 - Radiometric Method Practical",
"ESC253 - Geology  Practical",
"CEC207 - Design of Concrete Structures",
"ESC205 - Introduction Ecology and Environmental Microbiology",
"CEC206 - Structural Analysis - I",
"CEC209 - Transportation Engineering",
"CEC210 - Surveying Laboratory",
"ECC206 - Analog Circuits",
"MSD525 - Operations Analytics",
"ESE202 - Atmospheric  Science and Climate Change",
"EEC204 - Electrical Machines - I",
"PHD571 - Advanced Mathematical Methods in Physics",
"ECC309 - Microwave Engineering Lab",
"FMC206 - Phase Transformation and Heat Treatment",
"ECE201 - Measurements and Instrumentations",
"CSO304 - Digital Image Processing",
"ECC210 - Electronic Devices and Circuits Lab",
"PEC207 - Petroleum Formation Evaluation",
"ECC211 - Microprocessor & Microcontroller Lab",
"CHC308 - Chemical Process Equipment Design Lab",
"CEC208 - Geotechnical Engineering",
"CEC211 - Transportation Engineering Laboratory",
"CEE202 - Fluid Mechanics and Machines",
"CHD418 - Electrochemical Science and Engineering",
"ECC209 - Microprocessors & Microcontrollers",
"ECC207 - Electromagnetic Theory",
"CHC309 - Process Simulation Lab",
"ESC204 - Geology and Land use Planning",
"CHC307 - Process Modelling and Simulation",
"ESC207 - Air Pollution Control",
"MMC208 - Design of Mining Equipment Components",
"ECC208 - Control Systems",
"CHO301 - Petroleum Refining",
"EEC205 - Electrical Measurements",
"EEC206 - Control System Engineering",
"FMC253 - Fine Particle Processing Laboratory",
"MMC210 - Hydraulics & Pneumatics Lab",
"MME201 - IC Engines",
"MME201 - IC Engines",
"CEO525 - Optimization Methods",
"MMC209 - Hydraulics & Pneumatics",
"CEO303 - Construction Management",
"MEC211 - Machine Dynamics and Solid Modeling Lab",
"EEC207 - Power System Engineering",
"FMC205 - Thermodynamics and Kinetics",
"CYD520 - Advanced Fluorescence Spectroscopy",
"MEC210 - Heat Transfer and Fluid Machines Lab",
"FMC204 - Electrochemistry and Corrosion",
"MMC207 - Bulk Material Handling Equipment",
"CHC306 - Chemical Process Equipment Design",
"MCC205 - Linear Algebra",
"CEO527 - Bridge Engineering",
"CHO302 - Industrial Safety and Hazards Management",
"PHC210 - Electricity and Magnetism Lab",
"PHC209 - Optics Lab",
"FMC254 - Introduction to Fuel Technology Laboratory",
"MMC206 - Mine Electrical Technology",
"MCC512 - Operating Systems Practical",
"MEC207 - Dynamics of Machinery",
"MEC209 - Production Technology",
"CEC306 - Water Resources Engineering",
"MNC209 - Rock Mechanics Practical",
"ECC307 - Microwave Engineering",
"MCD401 - Computer Graphics",
"MNC210 - Mine Ventilation practical - I",
"MNC208 - Underground Coal Mining",
"PED503 - Enhanced Oil and Gas Recovery Methods",
"MCD508 - Theory of Computation",
"PHE202 - Material Science and Engineering",
"MNC207 - Underground Metal Mining",
"FMC207 - Fine Particle Processing for Coal and Minerals",
"CEC307 - Structural Detailing Laboratory",
"MEC208 - Heat and Mass Transfer",
"FME222 - Introduction to Fuel Technology",
"CSC305 - Computer Network",
"CEC308 - Water Resources Engineering Laboratory",
"CSC307 - Computer Networks Lab",
"MCD532 - Data Mining",
"MNC206 - Mine Ventilation",
"GLC510 - Metamorphic Petrology",
"MEC206 - Fluid Machines",
"MCC541 - Advanced DBMS Practical",
"MCO531 - Stochastic Processes",
"MCD516 - Industrial Statistics",
"CSC306 - Software Engineering",
"MSC528 - Machine Learning Lab",
"MCC509 - Statistical  Inference",
"MCC510 - Operating Systems",
"MCC539 - Advanced DBMS",
"MCO501 - Discrete Mathematics",
"PHC510 - Atomic and Molecular Physics",
"GLC208 - Economic Geology and Indian Mineral Deposits",
"MCC508 - Advanced Algebra",
"ECC306 - Digital Communication",
"GLC210 - Economic Geology Practical",
"GLC209 - Petrology Practical",
"GPC205 - Oceanography",
"MNC205 - Rock Mechanics",
"MSD515 - Services Marketing",
"PHC512 - Experimental Physics - III",
"CHC525 - Unit Operations for Pharmaceutics",
"PHC208 - Electrodynamics",
"MCE301 - Operations Research",
"FMD463 - Non Ferrous Extractive Metallurgy",
"MCC511 - Database Management Systems",
"ECC308 - Digital Communication Lab",
"GLC206 - Introduction to Stratigraphy and Paleontology",
"GLC207 - Descriptive Mineralogy",
"MSC511 - Organizational Behaviour",
"CSI101 - Computer Programming",
"HSI101 - Communication Skills",
"MCI102 - Mathematics - II",
"MCI103 - Numerical Methods",
"MEI102 - Manufacturing Processes",
"CYI101 - Chemistry",
"CSI102 - Computer Programming Lab",
"GPC530 - Seismology",
"CYI102 - Chemistry Lab",
"ESI101 - Environmental Sciences",
"HSI101 - Communication Skills",
"GPC531 - Geotechnical Modelling",
"MCI102 - Mathematics - II",
"GPC534 - Finite Element Analysis",
"MCI103 - Numerical Methods",
"MEI102 - Manufacturing Processes",
"GPC207 - Radiometric Method",
"GPC532 - Hydrology",
"CYD501 - Medicinal Chemistry",
"GPC533 - Seismic Hazard Zonation",
"GPC535 - Geotechnical Modelling Practical",
"GPC536 - Seismology Practical",
"CHC502 - Advanced Chemical Engineering Thermodynamics",
"MSC525 - Human Resources Management",
"CHC501 - Advanced Transport Phenomena",
"EEC377 - Power and Switchgear Lab",
"EEC378 - Power Electronics and Drives lab",
"MCD511 - Mathematical Ecology",
"EEC312 - Electrical Drives and Applications",
"CYD505 - Asymmetric Synthesis",
"MCC401 - Software Engineering",
"FMC501 - Coal and Mineral Processing",
"FMC504 - Unit Operations in Extractive Metallurgy",
"ESC503 - MATLAB Programming for Numerical Computation",
"ESC504 - Air and Noise Pollution",
"ESC505 - Wastewater Engineering",
"ESC521 - Water Chemistry Practical",
"ESC522 - Air and Noise Monitoring Practical",
"FMC502 - Transport Phenomena",
"FMC503 - Numerical Methods & Computer Applications",
"FMC551 - Coal and Mineral Processing Laboratory",
"FMC552 - Process Metallurgy Laboratory",
"FMC506 - Fuel Technology",
"MCC531 - Advanced Data Structures & Algorithm",
"MCC532 - Fundamentals of Machine Learning",
"MCC534 - Statistics in Decision Makings",
"MCC535 - Soft Computing Techniques",
"MCC533 - Computer Oriented Numerical Methods",
"MCC536 - Advanced Data Structures & Algorithm Practical",
"MCC537 - Fundamentals of Machine Learning Practical",
"PEC501 - Formation Evaluation and Production Logging",
"PEC503 - Numerical Methods for Petroleum Engineers",
"MCC538 - Computer Oriented Numerical Methods Practical",
"PEC502 - Advanced Well Testing",
"PEC504 - Advanced Production Technologies",
"PEC506 - Reservoir Simulation Practical",
"PEC505 - Petroleum Economics, Risk and Uncertainty Management",
"MCC502 - Differential Equations",
"MSC514 - Human Resources Management",
"MCC505 - Probability & Statistics",
"MCC503 - Numerical Methods",
"PEC507 - Term paper or Mini Project",
"MCC501 - Analysis",
"MCC504 - Data Structures",
"MCC506 - Numerical Methods Practical",
"GLC505 - Mathematics for Geoscientists",
"MCC507 - Data Structures Practical",
"GLC502 - Applied Geochemistry",
"GPC542 - Geophysical Field Theory",
"GLC553 - Geology of Natural Resources",
"GLC552 - Sample Preparation and Analytical Technique in Geosciences",
"GPC541 - Numerical Analysis and Data Structure",
"HSI500 - Research and Technical Communication",
"GPC531 - Geotechnical Modelling",
"CHC501 - Advanced Transport Phenomena",
"HSI500 - Research and Technical Communication",
"GPC513 - Geoelectrical Methods Practical",
"GPC533 - Seismic Hazard Zonation",
"CHC502 - Advanced Chemical Engineering Thermodynamics",
"CHC503 - Computational Techniques in Chemical Engineering",
"CHC519 - Catalytic Processes and Reactors",
"CHC520 - Applied Statistics in Chemical Engineering",
"PHD573 - Physics of Semiconducting Materials and Devices",
"FMC352 - Heat Treatment and Mechanical Metallurgy Laboratory",
"MCD535 - Bioinformatics",
"GPC512 - Seismic Data Acquisition Practical",
"MCC402 - Software Engineering Practical",
"PEC209 - Petroleum Product Testing Practical",
"GLC503 - Methods of Structural Geology",
"MCO502 - Optimization Techniques",
"GLC506 - Mineralogy and Geochemistry Practical",
"MCO401 - Partial Differential Equations",
"GLC502 - Applied Geochemistry",
"GLC504 - Micropaleontology and Vertebrate Palaeontology",
"GPC502 - Gravity Method",
"GLC508 - Micropaleontology and Vertebrate Paleontology Practical",
"GPC504 - Mathematical Functional Analysis",
"GPC505 - Gravity Method Practical",
"GLO532 - Environmental Geology",
"GPE202 - Geophysical Prospecting",
"GLC507 - Methods of Structural Geology Practical",
"GPE203 - Geophysical Prospecting Practical",
"MCC301 - Number Theory and Cryptography",
"GPC501 - Solid Earth Geophysics",
"GPC507 - Mathematical Functional Analysis Practical",
"MCC302 - GPU Computing Practical",
"GPO501 - Groundwater Geophysics",
"PHC511 - Condensed Matter Physics",
"MCD541 - GPU Computing",
"MCC502 - Differential Equations",
"GLC202 - Physical and Structural Geology",
"GPC501 - Solid Earth Geophysics",
"GLC203 - Crystallography and Optical Mineralogy Practical",
"MCO403 - Graph Algorithms",
"GPC204 - Self-Potential Method Theory & Application Practical",
"MSC515 - Software Lab",
"GPC523 - Geoelectromagnetic Method Practical",
"MCD502 - Graph Theory",
"MCD510 - Complex Analysis",
"MCC201 - Modern Algebra",
"GLE203 - Geology for Engineering and Sciences Practical",
"GLC201 - Crystallography and Mineralogy",
"GPC202 - Self-Potential Method: Theory and Application",
"GPC203 - Lab on Rock Physics",
"MCC202 - Computer Organization and Architecture",
"GLC204 - Structural Geology Practical",
"MCC203 - Real Analysis",
"GPE202 - Geophysical Prospecting",
"GLE201 - Geology for Engineering and Sciences",
"MCC505 - Probability & Statistics",
"CHD408 - Process Data Analytics",
"GLC202 - Physical and Structural Geology",
"CHD413 - Advanced Separation Processes",
"CHD405 - Energy Technology",
"GPC201 - Introduction to Rock Physics",
"CHO402 - Biofuels & Biomass Conversion Technology",
"MCC204 - Computer Organization and Architecture Practical",
"CHD415 - Interfacial Phenomena and Microfluidics",
"CHO404 - AI in Process Industries",
"CHO401 - Process Integration",
"CSO504 - Machine Learning",
"CSD407 - Network Security",
"CSD410 - Quantum Computing",
"ECD415 - Optical Communication",
"CSD502 - Cloud Computing",
"ECO502 - Neuromorphic Engineering",
"CSO404 - Cryptography",
"ECD401 - Antenna and Wave Propagation",
"ECD418 - Semiconductor Device Modeling and Simulation",
"ECO561 - Embedded System Design",
"CSO403 - Internet Technology",
"ECD405 - Digital Systems Design using HDL",
"ECD411 - Machine learning & Artificial Intelligence",
"ECO301 - Microprocessor and its Application",
"ECO302 - Power Electronics",
"GLC509 - Igneous Petrology",
"ESC357 - Solid Waste Management Practical",
"ESC312 - Geoinformatics",
"PHC205 - Introduction to Quantum Mechanics",
"MSC517 - Simulation Modelling & Analysis Lab",
"MCC513 - Database Management Systems Practical",
"GLC513 - Coal Geology",
"GLD571 - Petroleum Exploration and Micropalaeontology",
"GPC515 - Earthquake Seismology and Well Logging Practical",
"PHC513 - Experimental Physics - IV",
"GLC526 - Ore Geology",
"GLC533 - Ore Geology Practical",
"GLC516 - Coal Geology Practical",
"GLD594 - Geotechniques of Dams, Tunnels and Underground Space",
"GPC522 - Magnetic Method Practical",
"HSD513 - Introduction to Poetry",
"MNO401 - Rock Engineering",
"GPC510 - Well Logging",
"PHC509 - Electrodynamics and Radiation theory",
"ESC311 - Solid Waste Management",
"CYD502 - Polymer Chemistry",
"GPC206 - Mathematical Geophysics",
"GLC510 - Metamorphic Petrology",
"GPC511 - Seismic Data Acquisition",
"GPO503 - Artificial Intelligence and Machine Learning in Geosciences",
"GLD528 - Geotechnical Engineering",
"MSC524 - Marketing Management",
"GPC520 - Magnetic Method",
"MSC527 - Machine Learning",
"GLC515 - Sedimentology and Petroleum Geology Practical",
"GPC509 - Geoelectrical Method",
"GLD575 - Modern Instrumental Methods in Exploration Geosciences",
"GPC521 - Geoelectromagnetic Method",
"MSC512 - Operations Management",
"MSC513 - Marketing Management",
"GPD508 - Seismological Data Analysis",
"MSC510 - Corporate Finance",
"CSC308 - Software Engineering Lab",
"PEC210 - Drilling Simulation Practical",
"EEO302 - Industrial Utilization of Electrical Power",
"CSO302 - Graph Theory",
"MEC516 - Unconventional Manufacturing Processes",
"MSC531 - Managerial Ethics, Values and CSR",
"ESC358 - Geoinformatics Practical",
"MSO503 - International Macroeconomics and Monetary Policy",
"GPD507 - Geophysics for Mineral Exploration",
"GLO501 - Image Processing and Data Analysis",
"GPC508 - Earthquake Seismology",
"MSC510 - Corporate Finance",
"GPD505 - Near Surface Geophysics and Geotechnical Modelling",
"PHC206 - Applied Optics",
"CYC525 - Basic of Pharmacology & Drug Design",
"CHD504 - Process Optimization",
"MSD536 - Public Policy Analysis",
"MSD523 - Management of Self and Behavioural Analytics",
"CHC530 - Reaction Engineering",
"CHC531 - Chemical Engineering Lab",
"ESD404 - Water Resource Planning and Management",
"ESD513 - Energy Auditing and Management",
"CSC506 - Advanced Data Structures & Algorithms Lab",
"CSC507 - Computing Techniques and Mathematical Tools Lab",
"ECC583 - VLSI & Communication Systems Lab",
"ECC584 - RF & Photonics Lab",
"CYD528 - Modern Separation Techniques",
"CYC529 - Formulation/Manufacturing Lab",
"HSO310 - Psychology of Everyday Life",
"CEC305 - Design of Steel Structures",
"MSD504 - HR Analytics",
"FMC304 - Coal and Mineral Processing Plant Design",
"ESD508 - Social Impact Assessment and R&R",
"HSI500 - Research and Technical Communication",
"CYD512 - Modern Aspects of Catalysis and Surface Science",
"CSI102 - Computer Programming Lab",
"MED545 - Turbomachinery",
"HSO505 - Social Entrepreneurship",
"CSI101 - Computer Programming",
"CSI101 - Computer Programming",
"CSI102 - Computer Programming Lab",
"HSI500 - Research and Technical Communication",
"MEI102 - Manufacturing Processes",
"HSI500 - Research and Technical Communication",
"FMD516 - Advanced Phase Transformation",
"MED513 - Thermo-Production Processes",
"MCD503 - Integral Equations and Calculus of Variations",
"GLC512 - Petroleum Geology",
"MEC308 - Computer Aided Manufacturing Lab",
"PEC206 - Elements of Petroleum Production Engineering",
"CYD531 - Biotechnology in Pharmaceutical Sciences",
"CYD506 - Computational Chemistry",
"MEC309 - Heat Power and Refrigeration Lab",
"MMC307 - Mining Machinery Lab",
"CYD529 - Computer Aided Drug Discovery",
"MSD514 - Financial Econometrics",
"ECC580 - Mathematical and Simulation Techniques",
"MCC503 - Numerical Methods",
"FMC303 - Mechanical Metallurgy",
"MSC529 - Big Data Lab",
"ECC501 - Advanced Optical Communication",
"ECC542 - Microwave Transmission Lines and Matching Networks",
"ECC500 - Advanced Communication Theory",
"MCC521 - Bayesian Survival Analysis",
"HSI500 - Research and Technical Communication",
"HSI500 - Research and Technical Communication",
"ECC501 - Advanced Optical Communication",
"CSI101 - Computer Programming",
"MEC307 - IC Engines and Gas Turbines",
"MCC521 - Bayesian Survival Analysis",
"GLC208 - Economic Geology and Indian Mineral Deposits",
"MCC512 - Operating Systems Practical",
"PEC208 - Reservoir Fluid Thermodynamics",
"MCD512 - Non-Linear Dynamics and Chaos",
"MCD557 - Finite Field Theory",
"MCC503 - Numerical Methods",
"MSD522 - Marketing Analytics",
"MEC306 - Computer Aided Manufacturing",
"MCC500 - Research Methodology",
"CYI102 - Chemistry Lab",
"CYI102 - Chemistry Lab",
"ESI101 - Environmental Sciences",
"HSI500 - Research and Technical Communication",
"GPC515 - Earthquake Seismology and Well Logging Practical",
"MCI103 - Numerical Methods",
"CYC511 - Group Theory & Electronic Spectroscopy",
"CHC506 - Instrumental Methods of Analysis",
"CYC508 - Kinetics and Thermodynamics",
"EEO301 - Microprocessor & Microcontroller",
"MSC519 - Project Management",
"CYI101 - Chemistry",
"CYD507 - Bio-inorganic Chemistry",
"MNC304 - Mine Legislation and Safety",
"HSD530 - Indian Philosophy of Mind",
"CSC504 - Computing Techniques and Mathematical Tools",
"ECC582 - Digital VLSI Circuits Design",
"MSC527 - Machine Learning",
"CYI101 - Chemistry",
"MED529 - Composite Materials",
"FMD461 - Computational Techniques and Modelling",
"MSD520 - Merchant Banking and Financial Services",
"MNC305 - Mine Automation and Data Analytics",
"FMC305 - Coal and Mineral Processing Plant Design Laboratory",
"MCC511 - Database Management Systems",
"ESD505 - Advanced Water and Wastewater Treatment",
"MNC306 - Mine Data Analytics Practical",
"ESI101 - Environmental Sciences",
"CYC509 - Methods in Organic Synthesis",
"ECC504 - Fundamentals of Communication Systems Design",
"CHC304 - Chemical Kinetics and Reaction Engineering Lab",
"FMO431 - Elements of Mineral Engineering",
"FMC506 - Fuel Technology",
"CSC502 - Advanced DBMS",
"CSC503 - Algorithmic Graph Theory",
"MCC502 - Differential Equations",
"MED554 - Surface Engineering",
"CHC505 - Advanced Process Control",
"CHC303 - Process Design and Economics",
"CYD530 - Pharmacovigilance and Regulatory Affairs",
"ECC305 - Communication System Lab",
"CSO303 - Artificial Intelligence",
"MCD504 - Measure Theory",
"HSI101 - Communication Skills",
"MSC527 - Machine Learning",
"HSI101 - Communication Skills",
"MCI102 - Mathematics - II",
"MEO302 - Refrigeration and Air-conditioning",
"ESC501 - Ecology and Environmental Microbiology",
"HSC502 - Fundamentals of Data Analysis",
"CSC505 - High Performance Computer Architecture",
"MCC513 - Database Management Systems Practical",
"EEC311 - Power System Analysis and Control",
"MNC307 - Numerical Modelling/Remote Sensing & GIS Practical",
"GPC518 - Geophysical Inversion Practical",
"GLD576 - Nanotechnology in Mineral and Hydrocarbon Exploration",
"GLD591 - Rock Slope Engineering",
"GPC519 - Seismic Data Processing and Interpretation  Practical",
"FMD401 - Powder Metallurgy",
"MCC502 - Differential Equations",
"PEC503 - Numerical Methods for Petroleum Engineers",
"GPC517 - Seismic Data Processing and Interpretation",
"GPC510 - Well Logging",
"PEO401 - Petroleum Environment, Health and Safety Practices",
"CSC518 - Number Theory and Cryptography",
"GLC503 - Methods of Structural Geology",
"MSD519 - International Finance",
"GLC516 - Coal Geology Practical",
"FMC501 - Coal and Mineral Processing",
"CSC202 - Discrete Mathematics",
"ESD405 - Climate Vulnerability and Risk Analysis",
"ECC505 - Numerical Methods and Optimization Techniques",
"ESC355 - Environmental Geotechnology Practical",
"CSC204 - Data Structures Lab",
"CSE201 - Data Structures and Algorithms",
"PED403 - Drilling System Design",
"GLC502 - Applied Geochemistry",
"GPC507 - Mathematical Functional Analysis Practical",
"GPC503 - Remote Sensing Principles",
"FMD403 - Engineering Materials Selection and Design",
"GPD503 - Image Processing and Geographic Information System",
"MCC509 - Statistical  Inference",
"MCC510 - Operating Systems",
"ESC356 - Wastewater Engineering Practical",
"MSD521 - Consumer Behaviour",
"GLC507 - Methods of Structural Geology Practical",
"GLC519 - Engineering Geology",
"GPC516 - Geophysical Inversion",
"CSC517 - Selected Topics in Algorithms",
"GLC508 - Micropaleontology and Vertebrate Paleontology Practical",
"FMO544 - Clean Coal Technology",
"GLC504 - Micropaleontology and Vertebrate Palaeontology",
"GLC520 - Hydrogeology",
"GLC518 - Principles and Applications of Geostatistics",
"GLC525 - Engineering Geology and Hydrogeology Practical",
"GLC524 - Principles and Applications of Geostatistics Practical",
"GLC506 - Mineralogy and Geochemistry Practical",
"GPC518 - Geophysical Inversion Practical",
"CSC304 - Compiler Design Lab",
"CSC302 - Compiler Design",
"GLC501 - Advanced Mineralogy",
"CSC504 - Computing Techniques and Mathematical Tools",
"ESC251 - Water Pollution Practical",
"CYC512 - Physical Chemistry Lab - I",
"CSC303 - Database Management Systems Lab",
"PEO402 - Well Performance",
"GPC504 - Mathematical Functional Analysis",
"GPC517 - Seismic Data Processing and Interpretation",
"PED402 - Enhanced Oil Recovery Techniques",
"GLC519 - Engineering Geology",
"GLC505 - Mathematics for Geoscientists",
"GPC516 - Geophysical Inversion",
"PED401 - Offshore Drilling and Petroleum Production Practices",
"PEC504 - Advanced Production Technologies",
"PEC513 - Introduction to Python and Petroleum Data Analysis",
"GLD522 - Coalbed Methane, Shale Gas and Gas Hydrate Exploration",
"CSC503 - Algorithmic Graph Theory",
"MCC520 - Fourier Analysis and its Applications",
"ECE301 - Analog Interface Electronics",
"GPD502 - Formation Evaluation",
"GLC202 - Physical and Structural Geology",
"PHC508 - Quantum Mechanics",
"GPC506 - Remote Sensing Principles Practical",
"GLC520 - Hydrogeology",
"ECC582 - Digital VLSI Circuits Design",
"PEO406 - Reservoir Geomechanics",
"GPC505 - Gravity Method Practical",
"CHC302 - Chemical Kinetics and Reaction Engineering",
"ECC301 - Principles of Communication Systems",
"ESC501 - Ecology and Environmental Microbiology",
"ECC303 - VLSI Design",
"ESO405 - Cleaner  Energy",
"GPD501 - Geothermics and Geodynamics",
"ESD401 - Biodiversity Conservation",
"GPC502 - Gravity Method",
"ESD502 - Environmental Biotechnology",
"HSO308 - Social Psychology",
"GLD521 - Stratigraphy",
"ECD403 - Computer Networks",
"ESC309 - Wastewater Treatment",
"ESC310 - Environmental Impact Assessment",
"ESC308 - Environmental Geotechnology",
"GLC518 - Principles and Applications of Geostatistics",
"GPC519 - Seismic Data Processing and Interpretation  Practical",
"GPC501 - Solid Earth Geophysics",
"ESC503 - MATLAB Programming for Numerical Computation",
"ESC202 - Air Pollution",
"GLC205 - Introduction to Petrology",
"CHC301 - Separation Processes",
"ESD511 - Aerosols in the Atmosphere",
"MCC506 - Numerical Methods Practical",
"CSC301 - Database Management Systems",
"CHC305 - Mass Transfer Lab",
"MCC520 - Fourier Analysis and its Applications",
"FMD517 - Mechanical Behaviour of Materials",
"GLO523 - Atmosphere, Ocean and Climate Dynamics",
"GLC525 - Engineering Geology and Hydrogeology Practical",
"MCC519 - Design and Analysis of Algorithms  Practical",
"FMC503 - Numerical Methods & Computer Applications",
"FMO547 - Additive Manufacturing",
"ESC203 - Noise  Pollution and Control",
"ECC202 - Signals & Networks",
"FMC510 - Mathematical Modeling of Mineral and Metallurgical Processes",
"PHC207 - Nuclear Science and Engineering",
"CSO505 - Soft Computing",
"ECC201 - Electronic Devices",
"ECC304 - Digital Signal Processing Lab",
"ECC302 - Digital Signal Processing",
"ECE301 - Analog Interface Electronics",
"FMC351 - Extractive Metallurgy Laboratory",
"ESD501 - Environmental Geology and Resource Management",
"FMC306 - Coal and Mineral Process Equipment Selection Laboratory",
"GLC524 - Principles and Applications of Geostatistics Practical",
"FMC301 - Coal and Mineral Process Equipment Selection",
"FMC302 - Extractive Metallurgy",
"CHD407 - Materials Characterization",
"GPD504 - Airborne Geophysics",
"PHD572 - Laser and Nonlinear Optics",
"MCC503 - Numerical Methods",
"ESC508 - Instrumental Techniques in Environmental Analysis",
"ECC203 - Digital Circuits and System Design",
"ECC204 - Digital System Design Lab",
"FMC509 - Advanced Materials and Applications",
"ESC525 - Environmental Chemistry",
"PHO572 - Photonics and Fibre Optics",
"PHD507 - Plasma and Space Physics",
"MSC519 - Project Management",
"MSD512 - Service Operations Management",
"PHD574 - Advanced Materials and Energy Devices",
"MMC308 - Pumps Fans & Compressors Lab",
"PEC308 - Enhanced Oil Recovery Practical",
"PEC309 - Reservoir Characterization Practical",
"CHD404 - Bioprocess Technology",
"CHD411 - Catalytic Reaction Engineering",
"CSD404 - Computer Graphics",
"GPC555 - Research Methodology and Statistics",
"CHC518 - Research Methodology",
"FMC511 - Research Methodology",
"ECC581 - Research Methodology",
"CEO528 - Ground Improvement and Geosynthetics",
"MNC700 - Research Methodology",
"PEC520 - Research Methodology",
"MMC591 - Research Methodology and Statistics",
"CHC511 - Term Paper and Presentation",
"CHD502 - Nanotechnology",
"CHC530 - Reaction Engineering",
"CHC531 - Chemical Engineering Lab",
"GPD522 - Computational Seismology",
"FMC203 - Physical Separation Processes for Coal and Minerals",
"ESC201 - Drinking Water Supply and Treatment",
"FMC201 - Colloids and Interfacial Phenomena",
"ESC252 - Air and Noise Pollution Practical",
"FMC252 - Physical Separation Processes Laboratory",
"ECC205 - Signals & Networks Lab",
"FMC202 - Heat and Mass Transfer",
"MSD507 - Management of Banks and Financial Institutions",
"GLE203 - Geology for Engineering and Sciences Practical",
"MSD503 - Sales and Distribution Management",
"MSD511 - Human Resources Development",
"ESE201 - Pollution Control and Management",
"PEC201 - Drilling Technology",
"MSD532 - Computational Finance",
"FMC251 - Particle Technology Laboratory",
"MSD508 - Advertising and Promotion Management",
"FME221 - Particle Technology",
"CYC516 - Strategies in Organic Synthesis",
"MSD510 - Personnel Management and Industrial Relations",
"MSD530 - Supply Chain Management and Logistics",
"CYC518 - Analytical Chemistry Lab",
"CYC515 - Molecular Spectroscopy",
"CYD532 - Solid State Materials: Chemistry & Engineering",
"MSD533 - Marketing Research",
"CYC517 - Physical Chemistry Lab - II",
"MCC514 - Functional Analysis",
"CYC514 - Photochemistry & Pericyclic Reactions",
"CYD535 - Main Group Chemistry",
"CYD536 - Science of Corrosion & Corrosion Control",
"CYD534 - Heterocyclic Chemistry",
"MCC515 - Topology",
"CYD522 - Advanced Biocatalysis",
"MCC516 - Computational Fluid Dynamics",
"CEC502 - Research Methodology and Statistics",
"PHC515 - Laser Physics and Technology",
"MCC517 - Design and Analysis of Algorithms",
"MCC518 - Computational Fluid Dynamics Practical",
"PHC517 - Computation and Simulation",
"CYC502 - Organic Reactions and Stereochemistry",
"PHD510 - Quantum Computation and Information",
"PHC514 - Statistical Mechanics",
"CYC504 - Application of Spectroscopic Methods",
"PHC516 - Nuclear and Particle Physics",
"CYC506 - Inorganic Chemistry lab",
"MCD514 - Sampling Theory",
"CYC503 - Mathematics for Chemists",
"CYC501 - Quantum Chemistry",
"CYC507 - Organic Chemistry Lab - I",
"PHC518 - Experimental Physics - V",
"PHC505 - Numerical Methods and Computer Programming",
"PHD501 - Advanced Quantum Mechanics",
"CYC505 - Coordination Chemistry",
"PHC502 - Methods of Mathematical Physics",
"PHC501 - Classical Mechanics and Special Theory of Relativity",
"PHC503 - Optics and Optical Instrumentation",
"CYC523 - Numerical Analysis and Methods in Chemistry",
"CEC512 - Applied Engineering Statistics",
"EEC511 - Renewable Energy Sources",
"PHC507 - Experimental Physics - II",
"HSI500 - Research and Technical Communication",
"HSI500 - Research and Technical Communication",
"CYC524 - Advanced Spectroscopic Methods",
"CYC515 - Molecular Spectroscopy",
"HSI500 - Research and Technical Communication",
"PHC506 - Experimental Physics - I",
"CEC503 - Mechanics of Deformable Solids",
"CEC513 - River Engineering",
"CYC522 - Advanced Techniques in Materials Characterization",
"CEC504 - Mechanics of Geomaterials",
"CEC501 - Numerical Methods in Civil Engineering",
"PHC504 - Electronics",
"EEC522 - Electromagnetic Compatibility of Power Converters",
"MSC508 - Business Analytics Lab",
"EEC521 - Battery Management Systems",
"EEC503 - Numerical Simulation for Electrical Engineering",
"MSC512 - Operations Management",
"MSC507 - Decision Modelling",
"MSC504 - Financial Accounting and Reporting",
"CEO301 - Reliability and Risk Assessment",
"CED401 - Traffic Engineering and Management",
"MSC518 - Productivity Management Lab",
"EED401 - Power System Protection and Switchgear",
"MSC521 - Productivity Management",
"CEO401 - Flow and Transport through Porous Media",
"EED403 - Industrial Power Electronics",
"CED501 - Computational Solid Mechanics",
"EED503 - Digital Control of Power Electronics & Drives",
"EED404 - Reactive Power and Voltage Control",
"MND406 - Mine Environmental Engineering",
"CED531 - Advanced Design of Structures",
"MSD506 - Investment Analysis and Portfolio Management",
"CEO528 - Ground Improvement and Geosynthetics",
"MSD513 - Managerial Psychology",
"MND401 - Advanced Mine Ventilation",
"MED505 - Fundamental of Classical and Statistical Thermodynamics",
"EEO403 - Digital Signal Processing",
"EEO404 - Renewable Energy Systems and Energy Audit",
"EEO405 - Industrial Automation",
"MND400 - Rock Excavation Engineering",
"MND403 - Geospatial Technology in Mining",
"MND404 - Mine System Engineering",
"MND405 - Mine Safety Engineering",
"MED527 - Design of Tribological Components",
"MND402 - Open Pit Slope Analysis and Design",
"MED403 - Power Plant Engineering",
"MED549 - Cryogenic Engineering",
"MED553 - Laser Processing of Materials",
"MMD505 - Fluid Flow Machines in Mines",
"MED540 - Fundamentals of Aeroacoustics",
"MED503 - Finite Element Method",
"PHO504 - Optoelectronic Materials and Devices",
"MEO534 - Automation and Control",
"PHO302 - Introduction to Astrophysics and Astronomy",
"MED401 - Energy Conversion Equipment",
"CEC304 - Geotechnical Engineering Laboratory",
"MED529 - Composite Materials",
"PHD509 - Advanced Condensed Matter Physics",
"CEC302 - Foundation Engineering",
"CEC301 - Structural Analysis - II",
"PHD506 - Characterization Techniques",
"CEC303 - Structural Engineering Laboratory",
"CEO528 - Ground Improvement and Geosynthetics",
"EEC309 - Modern Control",
"CED536 - Water Resources Systems Planning & Management",
"EEE202 - Utilization of Electrical Energy",
"HSO301 - Ethical Issues in Sceince",
"EED402 - High Voltage Engineering and Applications",
"HSO309 - Fundamental of Sociology",
"EEC310 - Power Electronics",
"EEC308 - Electrical Machines - II",
"EEC376 - Electrical Machines and Control Lab",
"EEC375 - Microprocessor and Microcontrollers Lab",
"HSO310 - Psychology of Everyday Life",
"MNC300 - Surface Mining",
"HSO501 - Cognitive Psychology",
"HSO510 - Judgement and Decision Making",
"MNC301 - Mine Planning and Economics",
"HSO506 - Indian Society and Culture",
"EEC272 - Analog and Digital Electronics Lab",
"MEC202 - Fluid Mechanics",
"GLE203 - Geology for Engineering and Sciences Practical",
"MNE201 - Introduction to Mining",
"EEE202 - Utilization of Electrical Energy",
"MNC201 - Rock Breakage",
"MEC201 - Kinematics of Machines",
"MNC202 - Mine Surveying",
"MNC200 - Elements of Mining",
"MME202 - Mining Machinery",
"MEE201 - Engineering Materials",
"MMC203 - Design of Machine Elements",
"MMC205 - Solid Mechanics and Theory of Machines Lab",
"MEC205 - Thermodynamics and Fluid Mechanics Lab",
"MEC203 - Applied Thermodynamics",
"MNC204 - Rock Breakage Practical",
"MNC203 - Mine Surveying Practical",
"MMC201 - Manufacturing Technology",
"MMC202 - Theory of Machines",
"MEC204 - Applied Mechanics Lab",
"MMC204 - Thermodynamics and Fluid Mechanics Lab",
"CYD528 - Modern Separation Techniques",
"CYC529 - Formulation/Manufacturing Lab",
"PEO302 - Oil & Gas Field Development and Planning",
"CHC205 - Fluid and Particle Mechanics Lab",
"PEC305 - Process Engineering Practical",
"CHC204 - Computational Tools for Chemical Engineers Lab",
"ECD404 - Digital Image Processing",
"ECD419 - Satellite Communication",
"ESD511 - Aerosols in the Atmosphere",
"PHC510 - Atomic and Molecular Physics",
"HSI500 - Research and Technical Communication",
"HSI500 - Research and Technical Communication",
"HSI500 - Research and Technical Communication",
"CED531 - Advanced Design of Structures",
"PEE201 - Introduction to Petroleum Engineering",
"PHC304 - Spectroscopy Lab",
"MMC305 - Underground Mining Equipment",
"PED404 - Petroleum Engineering Design",
"PHC303 - Applied Optics Lab",
"MMC306 - Opencast Mining Equipment",
"CSD401 - Advanced Algorithms",
"CSC508 - Computing Lab - I",
"PEO502 - Flow Assurance",
"CYD527 - Pharmacognosy and Phytopharmaceuticals",
"PEC306 - Directional Drilling",
"CYD531 - Biotechnology in Pharmaceutical Sciences",
"MED550 - Combustion and Emission in I C Engines",
"EEO505 - Modern Sensors and Signal Contioning Circuits",
"CYD529 - Computer Aided Drug Discovery",
"PHC302 - Solid State Physics",
"PEO301 - Heat and Mass Transfer in Petroleum Operations",
"PHO301 - Low Temperature Physics & Superconductivity",
"PEC303 - Natural Gas Engineering",
"PEC307 - Oil and Gas Well Testing",
"ECD405 - Digital Systems Design using HDL",
"MCC500 - Research Methodology",
"ESD402 - Industrial Waste Water Engineering",
"GPC523 - Geoelectromagnetic Method Practical",
"PHO302 - Introduction to Astrophysics and Astronomy",
"FMD536 - Surface Engineering",
"GLC534 - Exploration Geology Practical",
"GPD509 - Well Log and Electrofacies Analysis",
"CYC540 - Research Methodology and Statistics",
"CHC510 - Advanced Chemical Engineering Lab",
"GPC512 - Seismic Data Acquisition Practical",
"CSD521 - Wireless Networks",
"PED405 - Pipeline Engineering",
"GPC540 - Advanced Numerical Methods Practical",
"CSC205 - Computer Organization Lab",
"MSO502 - Management of Cryptocurrency",
"HSC503 - Seminar",
"CHC509 - Computational Fluid Dynamics",
"PHC204 - Waves and Acoustics Lab",
"PHC201 - Classical Mechanics",
"CSD508 - Distributed Systems",
"EED513 - Power Quality",
"EED511 - Power System Dynamics",
"EED405 - Instrumentation",
"CSC201 - Data Structures",
"CSC203 - Computer Organization",
"GLC591 - Research Methodology",
"PHC202 - Mathematical Physics",
"GPC538 - Advanced Numerical Methods",
"GLD544 - Kinematics of Rock Deformation",
"GLC533 - Ore Geology Practical",
"GLC526 - Ore Geology",
"GPC537 - Remote Sensing: Principles and Data Acquisition System",
"PHC203 - Mechanics Lab",
"MED525 - Rotor Dynamics",
"CSD517 - Parallel Computing",
"GLC527 - Exploration Geology and Mineral Economics",
"GPC521 - Geoelectromagnetic Method",
"GLD531 - Sequence Stratigraphy and Basin Analysis",
"GPD510 - Reservoir Geophysics and Deep Water Imaging",
"GPC520 - Magnetic Method",
"EED406 - Special Purpose Electric Machines and Drives",
"ESC526 - Research Methodology",
"MED555 - Computer Aided Manufacturing and Robotics",
"MEO528 - Robotics",
"PEO405 - Integrated Reservoir Management",
"GPO511 - Satellite Image Processing and Geographic Information System",
"PEO404 - Petroleum Resource Management and Project Evaluation",
"CHE201 - Engineering Thermodynamics",
"PEC304 - Petroleum Production Engineering Practical",
"CSO505 - Soft Computing",
"PHO571 - Materials Characterization",
"GPO510 - Strong Motion Seismology and Structural Responses",
"PED406 - Reservoir Modeling and Simulation",
"FMD522 - Coal Preparation",
"CSO506 - Principles of Blockchain Technologies",
"CSC516 - Research Methodology",
"CEO526 - Geoinformatics for Civil Engineering",
"GPC509 - Geoelectrical Method",
"CYD530 - Pharmacovigilance and Regulatory Affairs",
"HSC503 - Seminar",
"CHC508 - Advanced Mass transfer",
"GLD530 - Geodynamics",
"HSC503 - Seminar",
"CED404 - Environmental Engineering - II",
"MEC591 - Research Methodology and Statistics",
"PHC571 - Research Methodology and Statistics",
"MMO504 - Advanced Fluid Power Systems and Control",
"PHE200 - Biomedical Engineering",
"GLO545 - Radiogenic and Stable Isotope Geology",
"CSD514 - Mobile and Wireless Network Security",
"PED502 - Well Intervention, Workover and Stimulation Techniques",
"GPC511 - Seismic Data Acquisition",
"GPC539 - Remote Sensing: Principles and Data Acquisition System Practical",
"MEO522 - Condition Monitoring of Machines",
"MED547 - Convective and Two-phase Flow",
"GPD520 - Earthquake Statistics and Hazard",
"MED531 - Fracture Mechanics",
"EEC550 - Research Methodology and Statistics for Electrical Engineering",
"CHO501 - Rheology",
"MED541 - Microfluidics",
"MND411 - Advanced Underground Mining Methods",
"FMD518 - Joining of Materials",
"PHO501 - Astrophysics and Cosmology",
"FMO545 - Equipment Design",
"CHC201 - Chemical Process Calculations",
"CHC203 - Heat Transfer",
"PEC301 - Applied Petroleum Reservoir Engineering and Management",
"CSD510 - Information Retrieval",
"ESD501 - Environmental Geology and Resource Management",
"MND408 - Innovative Mining Systems",
"PEC302 - Petroleum Production Operations",
"MCI103 - Numerical Methods",
"CHC202 - Fluid and Particle Mechanics",
"PHC200 - Waves and Acoustics",
"CSD509 - Image and Video Processing",
"MEI102 - Manufacturing Processes",
"CSD513 - Internet of Things",
"CSD505 - Cryptography and Network Security",
"CYI102 - Chemistry Lab",
"CYI101 - Chemistry",
"CHC507 - Computational Techniques Lab",
"EEO504 - Condition Monitoring of Electrical Machines",
"CSI102 - Computer Programming Lab",
"HSC502 - Fundamentals of Data Analysis",
"ESI101 - Environmental Sciences",
"MND556 - Computational Geomechanics",
"HSC502 - Fundamentals of Data Analysis",
"HSC502 - Fundamentals of Data Analysis",
"MCI102 - Mathematics - II",
"GLC208 - Economic Geology and Indian Mineral Deposits",
"CHC503 - Computational Techniques in Chemical Engineering",
"CHC504 - Advanced Chemical Reaction Engineering",
"GPC508 - Earthquake Seismology",
"CSC501 - Advanced Data Structures & Algorithms",
"MND410 - Advanced Blasting Techniques",
"MEC500 - Theory of Elasticity",
"MSC530 - Development Economics",
"MSC502 - Research Methodology and Statistics",
"MEC502 - Numerical Methods",
"MSC530 - Development Economics",
"MSC512 - Operations Management",
"PHC574 - Numerical Methods and Simulation",
"MSC531 - Managerial Ethics, Values and CSR",
"PHC575 - Physics of Phase Transformation",
"HSI500 - Research and Technical Communication",
"HSI500 - Research and Technical Communication",
"PHC572 - Theoretical Physics",
"MSC502 - Research Methodology and Statistics",
"PHC573 - Experimental Physics",
"MSC506 - Managerial Economics",
"CYC518 - Analytical Chemistry Lab",
"CYC523 - Numerical Analysis and Methods in Chemistry",
"CYC528 - Process Chemistry Lab",
"CYC527 - Formulation & Drug Delivery Technology",
"CEC501 - Numerical Methods in Civil Engineering",
"EEC502 - Modelling of Electrical Machines",
"CYC526 - Pharmaceutical Process Technology",
"EEC506 - Advanced Electrical Machine Lab",
"CEC503 - Mechanics of Deformable Solids",
"CEC507 - Computational Laboratory",
"CEC504 - Mechanics of Geomaterials",
"EEC511 - Renewable Energy Sources",
"EEC504 - Advanced Control System",
"CEC505 - Engineering Hydrology & Hydraulics",
"EEC507 - Advanced Power System Lab",
"CEC506 - Transport System Design & Management",
"EEC512 - Soft Computing Techniques",
"CEC508 - Civil Engineering Model Development Laboratory",
"MNC537 - Computational Subsurface Ventilation and Environment Practical",
"EEC518 - Industrial Instrumentation",
"MNC536 - Computational Subsurface Ventilation and Environment",
"MEC508 - Advanced Heat Transfer",
"MEC594 - Basics of Scientific Computing",
"MEC595 - Thermal and Design Lab",
"MNC538 - Mass Production Mining Technology",
"MNC505 - Geomechanics Practical",
"MNC539 - Computational Geomechanics and Ground Control",
"MEC500 - Theory of Elasticity",
"MNC540 - Mining Equipment Reliability, Maintainability and Availability",
"MEC501 - Mechanical Vibration",
"MEC596 - Manufacturing and Tribology Lab",
"MEC514 - Advances in Machining",
"MSC502 - Research Methodology and Statistics",
"PEO506 - Carbon Capture And Sequestration Course Objective",
"CYD513 - Electroanalytical Methods",
"CYC513 - Organic Chemistry Lab - II",
"CYC510 - Organometallic Chemistry",
"CYO501 - Instrumental Techniques for Material Characterization",
"PEC205 - Drilling Fluids and Cementing Practical",
"PEC202 - Elements of Reservoir Engineering",
"PEC203 - Drilling Fluids and Cements",
"MSC501 - Management Principles & Practices",
"PEC204 - Reservoir Engineering Practical",
"PEE201 - Introduction to Petroleum Engineering",
"MSC502 - Research Methodology and Statistics",
"MSC502 - Research Methodology and Statistics",
"MSC526 - Strategic Management",
"HSC500 - Research and Technical Communication",
"MSC504 - Financial Accounting and Reporting",
"MSC522 - Data Mining for Business",
"HSC500 - Research and Technical Communication",
"MNC525 - Remote Sensing and Digital Image Processing",
"HSI500 - Research and Technical Communication",
"MSC504 - Financial Accounting and Reporting",
"MNC535 - Excavation Methods for Tunnels and Caverns",
"MSC523 - Multivariate Analysis Lab",
"MNO301 - Modern Surveying Techniques",
"MEO583 - Design of Thermal Systems",
"MMC304 - Automation and Control Lab",
"MSC506 - Managerial Economics",
"PHC301 - Electronics Lab",
"HSC501 - Research Methodology",
"MNC539 - Computational Geomechanics and Ground Control",
"HSC501 - Research Methodology",
"MSC508 - Business Analytics Lab",
"EEC202 - Analog and Digital Electronics",
"EEC271 - Networks Lab",
"MSC506 - Managerial Economics",
"HSC508 - Understanding Philosophy",
"HSC509 - Perspectives on Human Behaviour",
"HSC509 - Perspectives on Human Behaviour",
"HSC508 - Understanding Philosophy",
"MSC508 - Business Analytics Lab",
"MSC507 - Decision Modelling",
"MSC507 - Decision Modelling",
"MNO303 - Underground Construction Engineering",
"MMC301 - Mineral Beneficiation Equipment",
"MMC302 - Automation and Control in Mining Machineries",
"PHC300 - Thermal Physics Lab",
"PHC514 - Statistical Mechanics",
"PHO300 - Sensors and Transducers",
"MNC504 - Risk and Workplace Safety Management",
"ESC502 - Water Supply and Treatment",
"MED543 - Solar Energy",
"MEO580 - Measurements in Thermal Engineering",
"MEC301 - Machine Design",
"PHC515 - Laser Physics and Technology",
"MEC303 - Advanced Solid Mechanics",
"MSC509 - Business Communication Lab",
"HSC504 - Social Theory and Sociological Practices",
"MEC302 - Machining and Machine Tools",
"CEC205 - Environmental Engineering Laboratory",
"MED548 - Heat Exchanger Design",
"MED539 - Fundamentals of Aerodynamics",
"MMC303 - Mine Electrical Technology Lab",
"EEC203 - Electromagnetic Theory and Applications",
"CEE201 - Mechanics of Solid",
"CEC201 - Surveying",
"MNC303 - Mine Ventilation Practical - II",
"HSC504 - Social Theory and Sociological Practices",
"MEO522 - Condition Monitoring of Machines",
"MEC305 - Machine Design Lab",
"CSO503 - Data Mining",
"MNC302 - Computer Aided Mine Planning and Design",
"MMO301 - Automobile Engineering",
"MMD512 - Mine Electrical Drives",
"EEC201 - Signals, Systems and Networks",
"MNE201 - Introduction to Mining",
"CEC203 - Building Materials, Construction and Management",
"MEC304 - Production Technology Lab",
"CEC202 - Environmental Engineering",
"CEC204 - Material Testing Laboratory",
"MSD502 - Financial Analytics",
"MCD537 - Design of Experiments",
"CSC509 - Computing Lab - II"
]

module.exports = { courses_names };